version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-deps-{{ checksum "requirements.txt" }}
      - run:
          name: Run tests
          command: pytest

  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-deps-black
      - run:
          name: Install Black
          command: pip install black
      - save_cache:
          paths:
            - ~/.cache/pip
          key: v1-deps-black
      - run:
          name: Format code automatically
          command: black .

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - lint
