version: 2.1

commands:
  setup-environment:
    description: "Setup environment and caching"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "requirements.txt" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - save_cache:
          paths:
            - /home/circleci/.cache/pip
          key: v1-dependencies-{{ checksum "requirements.txt" }}

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup-environment
      - run:
          name: Run tests
          command: pytest -v

  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - setup-environment
      - run:
          name: Check code formatting with Black
          command: black --check --diff .

workflows:
  version: 2
  test-and-lint:
    jobs:
      - test
      - lint
