version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install -r requirements.txt
      - run: pytest

  lint:
    docker:
      - image: cimg/python:3.11
    steps:
      - checkout
      - run: pip install black
      - run: black --check .

workflows:
  version: 2
  build-and-test:
    jobs:
      - test
      - lint
